name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        cc: [gcc, clang]
        mpfp: [enable-mpfp]

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: |
        sudo apt-get install libpari-dev pari-gp2c libntl-dev
        wget https://flintlib.org/download/flint-3.5.0.tar.gz
        tar xf flint-3.5.0.tar.gz
        cd flint-3.5.0
        ./configure
        make -j 8
        make install
        sudo ldconfig
        cd ..
        ./autogen.sh
        ./configure --with-boost="no" --with-flint --disable-allprogs --${{ matrix.mpfp }}
      env:
        CC: ${{ matrix.cc }}
    - name: make
      run: make
    - name: make check
      run: make check
