name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        cc: [gcc, clang]
        mpfp: [enable-mpfp, disable-mpfp]

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
        sudo apt-get install libpari-dev pari-gp2c libntl-dev libflint-dev
        ./autogen.sh
        ./configure --with-boost="no" --with-flint --disable-allprogs --${{ matrix.mpfp }}
      env:
        CC: ${{ matrix.cc }}
    - name: make
      run: make
    - name: make check
      run: make check
