name: conda C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{ matrix.os }} with ${{ matrix.mpfp }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macos-latest"]
        mpfp: [enable-mpfp]

    steps:
    - uses: actions/checkout@v4
    - name: Install Xcode command-line tools
      run: |
        xcode-select --install || true
        sudo xcode-select --switch /Library/Developer/CommandLineTools
        sudo xcode-select --reset
        
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-version: latest
        mamba-version: "*"
        activate-environment: eclib-deps
        
    - name: configure
      shell: bash -el {0}
      run: |
        mamba install "pari>=2.16" ntl libflint compilers automake autoconf m4 libtool
        conda activate eclib-deps
        echo PATH=$PATH
        # Add explicit compiler path setup
        export CC=$(which clang)
        export CXX=$(which clang++)
        ./autogen.sh
        ./configure --with-boost="no" --with-flint --with-ntl=$CONDA_PREFIX --disable-allprogs --${{ matrix.mpfp }} CFLAGS="-fno-inline-asm"
    - name: make
      shell: bash -el {0}
      run: make
    - name: make check
      shell: bash -el {0}
      run: make check
